### ISSUE TITLE
Missing models for Person V2 tests

### ISSUE THREAD

**Issue by RobDickinson** [philterd/phileas#125]
These model files are very large and not provided by GitHub, and this causes the `EndToEndTestsHelper` to fail.

The easy workaround is to comment out references to `PersonV2` in the tests.

@jzonthemtn you already know about this issue, just documenting in case anybody else stumbles here before a fix is in place.

**Comment by jzonthemtn** [comment]
Added a commit in #127 to not fail due to missing models. This task should be to get the models back and not just mitigate the failing build.

**Comment by RobDickinson** [comment]
Apologies for taking so long to close but this is long since fixed. I'm building on x86 and arm64 without commenting out anything or skipping tests

**Comment by jzonthemtn** [comment]
Models are being made available at https://github.com/philterd/pii-models.
