### ISSUE TITLE
appliedSpans includes spans that didn't meet filter condition

### ISSUE THREAD

**Issue by RobDickinson** [philterd/phileas#126]
When a filter condition is set, it's expected that spans that failed to meet the filter condition would be included in `identifiedSpans` but not included in `appliedSpans`.

Here's a test case:
[https://github.com/resurfaceio/phileas-benchmark/blob/41b07620dd4b21cba9715d392154[…]1/src/test/java/ai/philterd/phileas/benchmark/RedactorTest.java](https://github.com/resurfaceio/phileas-benchmark/blob/41b07620dd4b21cba9715d39215400fddcded5b1/src/test/java/ai/philterd/phileas/benchmark/RedactorTest.java#L209)

ps. The actual string redaction in these cases is correct, it's only an issue if you're inspecting `FilterResponse.explanation()` directly

**Comment by jzonthemtn** [comment]
Thanks @RobDickinson. I can reproduce this.
