### ISSUE TITLE
Remove `S3PolicyService`

### ISSUE THREAD

**Issue by jzonthemtn** [philterd/phileas#167]
The `S3PolicyService` has substantial AWS dependencies and generally does not provide that much benefit in value. Remove it and use the `LocalPolicyService`.

**Comment by robfromboulder** [comment]
Nice 👍

It's much easier to add dependencies than to remove, so this is greatly appreciated!

**Comment by jzonthemtn** [comment]
Philter and Phileas used to be one application, and when I separated them awhile back I should have left more in Philter instead of putting the bulk in Phileas. So definitely trying to streamline Phileas and get out the bloat!
