### ISSUE TITLE
How to launch Phileas?

### ISSUE THREAD

**Issue by aindilis** [philterd/phileas#27]
Hi,

I am not very knowledgeable about Java, but much to my surprise I did manage to write a simple client using your instructions and get it to compile and run using Maven. However, I have not been able to figure out how to launch the Phineas service it expects at `https://127.0.0.1:8080`. I was wondering how to do that?

Cheers,
Andrew

**Comment by aindilis** [comment]
I found the command: `mvn --batch-mode --update-snapshots deploy`, but that leads to the following error:

```[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project phileas: Failed to retrieve remote metadata io.philterd:phileas:2.2.1-SNAPSHOT/maven-metadata.xml: Could not transfer metadata io.philterd:phileas:2.2.1-SNAPSHOT/maven-metadata.xml from/to github (https://maven.pkg.github.com/philterd/phileas): Authentication failed for https://maven.pkg.github.com/philterd/p\
hileas/io/philterd/phileas/2.2.1-SNAPSHOT/maven-metadata.xml 401 Unauthorized -> [Help 1]```

**Comment by jzonthemtn** [comment]
Hi @aindilis, the endpoint `https://127.0.0.1:8080` is used by Phileas for serving a model to identify person entities. This is enabled via the [Person's Names](https://docs.philterd.ai/philter/filters/filters/persons-names-1/persons-names-ner) filter. Only when that filter is included in a filter profile will that call be made.

We have been working to remove that external dependency and use the models inside of Phileas via ONNX Runtime -- https://github.com/philterd/phileas/blob/main/phileas-services/phileas-services-ai/src/main/java/ai/philterd/phileas/service/ai/onnx/OnnxNer.java. That code is still pretty new and experimental but it will work.

The filter that uses the ONNX Runtime is the `PersonsV2Filter` (https://github.com/philterd/phileas/blob/34cf9c012af01f39f00b94f2156177a30c017a78/phileas-core/src/main/java/ai/philterd/phileas/services/filters/ai/onnx/PersonsV2Filter.java#L24). It is possible to take a NER model from somewhere like Hugging Face Hub, convert it to ONNX, and then use it via this filter. We don't have good documentation for that yet but we are working on it.
